# Generated by Django 2.2.10 on 2020-11-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
    ]
