# Generated by Django 2.2.10 on 2020-11-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20201118_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_answer', to='polls.Question'),
        ),
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_answers', to='polls.Question'),
        ),
    ]
