# Generated by Django 2.2.10 on 2020-11-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201118_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text_answer'), ('sc', 'single_choice'), ('mc', 'multiple_choice')], max_length=2),
        ),
        migrations.DeleteModel(
            name='TypeQuestion',
        ),
    ]
