# Generated by Django 2.2.10 on 2020-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201118_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Ответ в виде текста'), ('sc', 'Ответ с выбором одного варианта'), ('mc', 'Ответ с выбором нескольких вариантов')], max_length=4),
        ),
    ]
