# Generated by Django 2.2.10 on 2020-11-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20201118_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choiceanswer',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='multichoiceanswer',
            old_name='choice_id',
            new_name='choice',
        ),
    ]
