# Generated by Django 2.2.10 on 2020-11-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_poll_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_answer', to='polls.Question'),
        ),
    ]
