# Generated by Django 2.2.10 on 2020-11-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20201119_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='name',
        ),
    ]
