# Generated by Django 2.2.10 on 2020-11-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20201124_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedquestion',
            name='completed_poll',
        ),
        migrations.RemoveField(
            model_name='completedquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='completedpoll',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='completedpoll',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_question', to='polls.Question'),
        ),
        migrations.AddField(
            model_name='completedpoll',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CompletedQuestion',
        ),
    ]
